import type { Doctor, Specialty, TimeSlot, Appointment, Review, User } from '@/lib/types'

export const MOCK_USER: User = {
  id: 'usr-1',
  email: 'alex.morgan@example.com',
  full_name: 'Alex Morgan',
  phone: '+1 (555) 234-5678',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  role: 'patient',
}

export const MOCK_SPECIALTIES: Specialty[] = [
  { id: 'spec-1', name: 'Cardiology', icon: 'Heart', color_hex: '#EF4444' },
  { id: 'spec-2', name: 'Neurology', icon: 'Brain', color_hex: '#8B5CF6' },
  { id: 'spec-3', name: 'Pediatrics', icon: 'Baby', color_hex: '#F59E0B' },
  { id: 'spec-4', name: 'Dermatology', icon: 'Sparkles', color_hex: '#10B981' },
  { id: 'spec-5', name: 'Orthopedics', icon: 'Bone', color_hex: '#3B82F6' },
  { id: 'spec-6', name: 'Ophthalmology', icon: 'Eye', color_hex: '#0ABDE3' },
  { id: 'spec-7', name: 'General Medicine', icon: 'Stethoscope', color_hex: '#6366F1' },
]

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    full_name: 'Dr. Sarah Jenkins',
    avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    specialty_name: 'Cardiology',
    specialty_icon: 'Heart',
    specialty: MOCK_SPECIALTIES[0],
    bio: 'Board-certified Cardiologist with over 12 years of experience in preventative heart care, non-invasive imaging, and cardiovascular wellness.',
    experience_years: 12,
    consultation_fee: 120,
    clinic_name: 'St. Jude Heart Center',
    clinic_address: '742 Evergreen Terrace, Medical Suite 300',
    rating_avg: 4.9,
    review_count: 128,
    gender: 'female',
    is_online_available: true,
    is_in_person_available: true,
    user: {
      id: 'u-doc-1',
      full_name: 'Dr. Sarah Jenkins',
      email: 'sarah.jenkins@cura.health',
      avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    },
  },
  {
    id: 'doc-2',
    full_name: 'Dr. Marcus Vance',
    avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    specialty_name: 'Neurology',
    specialty_icon: 'Brain',
    specialty: MOCK_SPECIALTIES[1],
    bio: 'Specialist in neurological disorders, migraine treatments, and cognitive health management.',
    experience_years: 15,
    consultation_fee: 150,
    clinic_name: 'Metropolitan Neurology Institute',
    clinic_address: '100 Broadway, 14th Floor',
    rating_avg: 4.8,
    review_count: 94,
    gender: 'male',
    is_online_available: true,
    is_in_person_available: true,
    user: {
      id: 'u-doc-2',
      full_name: 'Dr. Marcus Vance',
      email: 'marcus.vance@cura.health',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    },
  },
  {
    id: 'doc-3',
    full_name: 'Dr. Elena Rostova',
    avatar_url: 'https://images.unsplash.com/photo-1594824813566-88855ce78961?auto=format&fit=crop&w=400&q=80',
    specialty_name: 'Pediatrics',
    specialty_icon: 'Baby',
    specialty: MOCK_SPECIALTIES[2],
    bio: 'Compassionate pediatric specialist committed to infant nutrition, child development, and preventive care.',
    experience_years: 9,
    consultation_fee: 95,
    clinic_name: 'Sunshine Children Clinic',
    clinic_address: '45 Park Avenue, Suite 102',
    rating_avg: 4.95,
    review_count: 210,
    gender: 'female',
    is_online_available: true,
    is_in_person_available: true,
    user: {
      id: 'u-doc-3',
      full_name: 'Dr. Elena Rostova',
      email: 'elena.rostova@cura.health',
      avatar_url: 'https://images.unsplash.com/photo-1594824813566-88855ce78961?auto=format&fit=crop&w=400&q=80',
    },
  },
  {
    id: 'doc-4',
    full_name: 'Dr. David Chen',
    avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    specialty_name: 'Dermatology',
    specialty_icon: 'Sparkles',
    specialty: MOCK_SPECIALTIES[3],
    bio: 'Expert dermatologist specializing in medical skin disorders, acne solutions, and aesthetic laser treatments.',
    experience_years: 11,
    consultation_fee: 130,
    clinic_name: 'ClearSkin Aesthetics & Dermatology',
    clinic_address: '880 5th Avenue, Suite 500',
    rating_avg: 4.75,
    review_count: 87,
    gender: 'male',
    is_online_available: true,
    is_in_person_available: false,
    user: {
      id: 'u-doc-4',
      full_name: 'Dr. David Chen',
      email: 'david.chen@cura.health',
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    },
  },
]

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    appointment_id: 'app-101',
    patient_id: 'usr-1',
    doctor_id: 'doc-1',
    rating: 5,
    comment: 'Dr. Sarah was extremely attentive and answered all my questions thoroughly. Highly recommended!',
    created_at: '2026-08-20T14:30:00Z',
    patient_name: 'Alex Morgan',
  },
  {
    id: 'rev-2',
    appointment_id: 'app-102',
    patient_id: 'usr-2',
    doctor_id: 'doc-1',
    rating: 5,
    comment: 'Very professional environment and quick diagnostic feedback. Best cardiology clinic in the city.',
    created_at: '2026-08-15T11:00:00Z',
    patient_name: 'Emily Watson',
  },
  {
    id: 'rev-3',
    appointment_id: 'app-103',
    patient_id: 'usr-3',
    doctor_id: 'doc-2',
    rating: 4,
    comment: 'Great consultation for my chronic headaches. Clear medication plan provided.',
    created_at: '2026-08-10T09:15:00Z',
    patient_name: 'Robert Hayes',
  },
]

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'app-1',
    patient_id: 'usr-1',
    doctor_id: 'doc-1',
    slot_id: 'slot-1',
    consultation_type: 'online',
    status: 'scheduled',
    notes: 'Follow-up consultation regarding blood pressure readings.',
    created_at: '2026-09-01T10:00:00Z',
    doctor: MOCK_DOCTORS[0],
    slot: {
      id: 'slot-1',
      doctor_id: 'doc-1',
      slot_datetime: new Date(Date.now() + 86400000 * 2).toISOString(),
      duration_minutes: 30,
      is_booked: true,
    },
  },
  {
    id: 'app-2',
    patient_id: 'usr-1',
    doctor_id: 'doc-2',
    slot_id: 'slot-2',
    consultation_type: 'in_person',
    status: 'completed',
    notes: 'Annual neurological checkup.',
    created_at: '2026-08-15T14:00:00Z',
    doctor: MOCK_DOCTORS[1],
    slot: {
      id: 'slot-2',
      doctor_id: 'doc-2',
      slot_datetime: '2026-08-15T14:00:00Z',
      duration_minutes: 30,
      is_booked: true,
    },
  },
]
